# start FROM a baseline image of postgres v12.8
FROM postgres:12.8

# copy the sql script from ./scripts/db_init.sql to /docker-entrypoint-initdb.d/ 
# in the container. Whenever the container spins up, scripts in that directory get executed automatically.
# This will create and populate our database in the container.

COPY ./scripts/db_init.sql /docker-entrypoint-initdb.d/ 